# Generated by Django 5.1.3 on 2026-06-23 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='fact',
            name='invalidates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invalidated_by', to='feed.fact'),
        ),
        migrations.AddField(
            model_name='record',
            name='invalidates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invalidated_by', to='feed.record'),
        ),
    ]
